//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JigsawPuzzle.Wpf.WCFGameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFGameService.IGameService", CallbackContract=typeof(JigsawPuzzle.Wpf.WCFGameService.IGameServiceCallback))]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Test1", ReplyAction="http://tempuri.org/IGameService/Test1Response")]
        string Test1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Test1", ReplyAction="http://tempuri.org/IGameService/Test1Response")]
        System.Threading.Tasks.Task<string> Test1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/JoinGame", ReplyAction="http://tempuri.org/IGameService/JoinGameResponse")]
        System.Drawing.Bitmap JoinGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/JoinGame", ReplyAction="http://tempuri.org/IGameService/JoinGameResponse")]
        System.Threading.Tasks.Task<System.Drawing.Bitmap> JoinGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/ReadyGame")]
        void ReadyGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/ReadyGame")]
        System.Threading.Tasks.Task ReadyGameAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnlineUserMove")]
        void OnlineUserMove(JigsawPuzzle.Core.OperationType type);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnlineUserMove")]
        System.Threading.Tasks.Task OnlineUserMoveAsync(JigsawPuzzle.Core.OperationType type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Test2", ReplyAction="http://tempuri.org/IGameService/Test2Response")]
        string Test2();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/StartGame")]
        void StartGame(byte[] map);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/Move")]
        void Move(JigsawPuzzle.Core.OperationType type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : JigsawPuzzle.Wpf.WCFGameService.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.DuplexClientBase<JigsawPuzzle.Wpf.WCFGameService.IGameService>, JigsawPuzzle.Wpf.WCFGameService.IGameService {
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string Test1() {
            return base.Channel.Test1();
        }
        
        public System.Threading.Tasks.Task<string> Test1Async() {
            return base.Channel.Test1Async();
        }
        
        public System.Drawing.Bitmap JoinGame() {
            return base.Channel.JoinGame();
        }
        
        public System.Threading.Tasks.Task<System.Drawing.Bitmap> JoinGameAsync() {
            return base.Channel.JoinGameAsync();
        }
        
        public void ReadyGame() {
            base.Channel.ReadyGame();
        }
        
        public System.Threading.Tasks.Task ReadyGameAsync() {
            return base.Channel.ReadyGameAsync();
        }
        
        public void OnlineUserMove(JigsawPuzzle.Core.OperationType type) {
            base.Channel.OnlineUserMove(type);
        }
        
        public System.Threading.Tasks.Task OnlineUserMoveAsync(JigsawPuzzle.Core.OperationType type) {
            return base.Channel.OnlineUserMoveAsync(type);
        }
    }
}
